disabled = false
languageCode = "es"
languageName = "Español"
weight = 1
title = "Bienvenide a Audio Gusano"

[params]
isoCode = "es"
rtl = false
dateFormat = "2 January 2006"
logo = "worm.png"
secondaryLogo = "worm.png"
description = "Sonido subterráneo"

["params.author"]
image = "gusi.jpg"
name = "Audio Gusano"
headline = "Sonido subterráneo"
