disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Bienvenide a Audio Gusano"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "worm.png"
secondaryLogo = "worm.png"
description = "Sonido subterráneo"

  [params.author]
  links = [ ]

["params.author"]
image = "gusi.jpg"
name = "Audio Gusano"
headline = "Sonido subterráneo"
