colorScheme = "avocado"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
replyByEmail = false
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
firebase = { }
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }
defaultBackgroundImage = ""

[header]
layout = "basic"

[footer]
showMenu = true
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = "10"
showMoreLink = true
showMoreLinkDest = "/recitales/"
cardView = true
cardViewScreenWidth = true
layoutBackgroundBlur = false
disableHeroImageFilter = false
homepageImage = "under.jpg"

[article]
showDate = true
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = false
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = false
showTaxonomies = true
showCategoryOnly = false
showAuthorsBadges = false
showWordCount = false
showZenMode = false

[list]
showHero = true
layoutBackgroundBlur = false
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showSummary = false
showViews = false
showLikes = false
showTableOfContents = false
showCards = true
orderByWeight = true
groupByYear = true
cardView = true
cardViewScreenWidth = true
constrainItemsWidth = false
heroStyle = "background"

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = true
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = false
cardView = true

[term]
showHero = true
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = true
cardViewScreenWidth = true


custom_css = ["/css/music.css"]
custom_js = ["/js/music.js"]