name: Sync Dropbox and Deploy

on:
  schedule:
    - cron: '0 * * * *' # This runs every hour automatically
  workflow_dispatch:      # This adds a "Run" button so you can test it manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: pip install dropbox PyYAML
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install dropbox

      - name: Run Dropbox Sync Script
        env:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        run: python sync_dropbox.py

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true # Useful if you use SCSS/SASS

      - name: Build Hugo Site
        run: hugo --minify

      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_key: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: public
          cleanup: true # This makes Neocities match your folder exactly